zap_config:
  filename: "tmp/log"
  max_size: 5
  max_age: 400
  max_backups: 1000

database:
  mysql:
    addr: localhost
    port: 3306
    username: root
    password: zzrr2005
    db: chat
    charset: utf8mb4
    conn_max_lifetime: 1h
    conn_max_idle_time: 1h
    place: Asia%2FShanghai
    max_idle_conns: 10
    max_open_conns: 10

  redis:
    addr: localhost
    port: 3307
    username: root
    password:
    db: 0

server:
  host: localhost
  port: 8080

auth:
  jwt:
    secret-key: "lanshan-chat"
    expires-time: 360000

filter:
  dict_path: "./manifest/default_dict.txt"